# Generated by Django 2.2.12 on 2020-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
    ]
