# Generated by Django 2.2.12 on 2020-07-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
    ]
