# Generated by Django 2.2.12 on 2020-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200701_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='branch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
